using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using OpenTelemetry.Proxy.Models;

namespace OpenTelemetry.Proxy.Tests;

/// <summary>
/// A thin wrapper generator that calls MetadataExtractor methods and outputs
/// the extracted metadata as generated source, enabling property-based testing.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class TestMetadataExtractionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // [ActivitySource] on types
        var typeProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "OpenTelemetry.Proxy.ActivitySourceAttribute",
                predicate: (node, _) => node is TypeDeclarationSyntax,
                transform: MetadataExtractor.ExtractTypeMetadata)
            .Collect();

        // [Activity] on methods
        var activityMethodProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "OpenTelemetry.Proxy.ActivityAttribute",
                predicate: (node, _) => node is MethodDeclarationSyntax,
                transform: MetadataExtractor.ExtractActivityMethodMetadata)
            .Collect();

        // [ActivityName] on types or methods
        var activityNameProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "OpenTelemetry.Proxy.ActivityNameAttribute",
                predicate: (node, _) => node is MethodDeclarationSyntax or TypeDeclarationSyntax,
                transform: MetadataExtractor.ExtractActivityNameMetadata)
            .Collect();

        // [NonActivity] on methods
        var nonActivityProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "OpenTelemetry.Proxy.NonActivityAttribute",
                predicate: (node, _) => node is MethodDeclarationSyntax,
                transform: MetadataExtractor.ExtractNonActivityMetadata)
            .Collect();

        var combined = typeProvider
            .Combine(activityMethodProvider)
            .Combine(activityNameProvider)
            .Combine(nonActivityProvider);

        context.RegisterSourceOutput(combined, (spc, source) =>
        {
            var ((typeResults, activityMethodResults), activityNameResults) = source.Left;
            var nonActivityMethodResults = source.Right;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// TestMetadataExtraction output");

            foreach (var result in typeResults)
            {
                var t = result.Metadata;
                sb.AppendLine($"// TYPE: TypeFullName={t.TypeFullName}");
                sb.AppendLine($"// TYPE: ActivitySourceName={t.ActivitySourceName}");
                sb.AppendLine($"// TYPE: Kind={t.Kind}");
                sb.AppendLine($"// TYPE: IncludeNonAsync={t.IncludeNonAsyncStateMachineMethod}");
                sb.AppendLine($"// TYPE: SuppressInstrumentation={t.SuppressInstrumentation}");
                foreach (var tag in t.TypeTags)
                    sb.AppendLine($"// TYPE_TAG: TagName={tag.TagName} SourceName={tag.SourceName} Expression={tag.Expression}");
                foreach (var mi in t.Methods)
                    sb.AppendLine($"// METHOD_INFO: MethodName={mi.MethodName} HasActivity={mi.HasActivityAttribute} HasActivityName={mi.HasActivityNameAttribute} HasNonActivity={mi.HasNonActivityAttribute} IsAsync={mi.IsAsync} IsPublic={mi.IsPublic}");
                foreach (var diag in result.Diagnostics)
                    sb.AppendLine($"// DIAGNOSTIC: {diag.Descriptor.Id} {string.Join(", ", (IEnumerable<string>)diag.MessageArgs)}");
            }

            foreach (var result in activityMethodResults)
            {
                var m = result.Metadata;
                sb.AppendLine($"// ACTIVITY_METHOD: ContainingType={m.ContainingTypeFullName}");
                sb.AppendLine($"// ACTIVITY_METHOD: MethodName={m.MethodName}");
                sb.AppendLine($"// ACTIVITY_METHOD: ActivityName={m.ActivityName}");
                sb.AppendLine($"// ACTIVITY_METHOD: Kind={m.Kind}");
                sb.AppendLine($"// ACTIVITY_METHOD: SuppressInstrumentation={m.SuppressInstrumentation}");
                sb.AppendLine($"// ACTIVITY_METHOD: Mode={m.Mode}");
                foreach (var tag in m.InTags)
                    sb.AppendLine($"// ACTIVITY_METHOD_INTAG: TagName={tag.TagName} SourceName={tag.SourceName} Source={tag.Source} Expression={tag.Expression}");
                foreach (var tag in m.OutTags)
                    sb.AppendLine($"// ACTIVITY_METHOD_OUTTAG: TagName={tag.TagName} SourceName={tag.SourceName} Source={tag.Source} Expression={tag.Expression}");
                foreach (var diag in result.Diagnostics)
                    sb.AppendLine($"// DIAGNOSTIC: {diag.Descriptor.Id} {string.Join(", ", (IEnumerable<string>)diag.MessageArgs)}");
            }

            foreach (var result in activityNameResults)
            {
                if (result.Item is TypeMetadata tm)
                {
                    sb.AppendLine($"// ACTIVITYNAME_TYPE: TypeFullName={tm.TypeFullName}");
                    sb.AppendLine($"// ACTIVITYNAME_TYPE: ActivitySourceName={tm.ActivitySourceName}");
                    sb.AppendLine($"// ACTIVITYNAME_TYPE: Kind={tm.Kind}");
                }
                else if (result.Item is MethodMetadata mm)
                {
                    sb.AppendLine($"// ACTIVITYNAME_METHOD: ContainingType={mm.ContainingTypeFullName}");
                    sb.AppendLine($"// ACTIVITYNAME_METHOD: MethodName={mm.MethodName}");
                    sb.AppendLine($"// ACTIVITYNAME_METHOD: ActivityName={mm.ActivityName}");
                    sb.AppendLine($"// ACTIVITYNAME_METHOD: AdjustStartTime={mm.AdjustStartTime}");
                    sb.AppendLine($"// ACTIVITYNAME_METHOD: Mode={mm.Mode}");
                    foreach (var tag in mm.InTags)
                        sb.AppendLine($"// ACTIVITYNAME_METHOD_INTAG: TagName={tag.TagName} SourceName={tag.SourceName} Source={tag.Source} Expression={tag.Expression}");
                }
                foreach (var diag in result.Diagnostics)
                    sb.AppendLine($"// DIAGNOSTIC: {diag.Descriptor.Id} {string.Join(", ", (IEnumerable<string>)diag.MessageArgs)}");
            }

            foreach (var result in nonActivityMethodResults)
            {
                var m = result.Metadata;
                sb.AppendLine($"// NONACTIVITY_METHOD: ContainingType={m.ContainingTypeFullName}");
                sb.AppendLine($"// NONACTIVITY_METHOD: MethodName={m.MethodName}");
                sb.AppendLine($"// NONACTIVITY_METHOD: SuppressInstrumentation={m.SuppressInstrumentation}");
                sb.AppendLine($"// NONACTIVITY_METHOD: Mode={m.Mode}");
                foreach (var diag in result.Diagnostics)
                    sb.AppendLine($"// DIAGNOSTIC: {diag.Descriptor.Id} {string.Join(", ", (IEnumerable<string>)diag.MessageArgs)}");
            }

            spc.AddSource("TestMetadataExtraction.g.cs", sb.ToString());
        });
    }
}
