using Microsoft.CodeAnalysis;
using OpenTelemetry.Proxy.Models;
using System.Collections.Immutable;
using System.Text;
using RefKind = OpenTelemetry.Proxy.Models.RefKind;

namespace OpenTelemetry.Proxy;

internal static class InterceptorEmitter
{
    /// <summary>
    /// Main entry point: generates the complete interceptor source file and adds it to the compilation.
    /// </summary>
    public static void Emit(
        SourceProductionContext spc,
        Compilation compilation,
        ImmutableArray<InterceptCallSite> callSites,
        ImmutableArray<TypeMetadata> types)
    {
        if (callSites.IsDefaultOrEmpty) return;

        var assemblyName = compilation.AssemblyName ?? "Unknown";
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Emit InterceptsLocation attribute definition
        EmitInterceptsLocationAttribute(sb);

        // Wrap generated classes in a namespace
        sb.AppendLine("namespace OpenTelemetry.Proxy.Generated");
        sb.AppendLine("{");

        // Collect all distinct ActivitySource names needed
        var activitySourceNames = CollectActivitySourceNames(callSites, types);

        // Emit ActivitySourceHolder class
        if (activitySourceNames.Count > 0)
            EmitActivitySourceHolder(sb, activitySourceNames, assemblyName);

        // Group call sites by target method, then by containing type
        var methodGroups = GroupCallSitesByMethod(callSites);
        var typeGroups = GroupMethodsByContainingType(methodGroups);

        // Emit one file static class per target type to avoid name conflicts
        var typeIndex = 0;
        foreach (var (containingType, methods) in typeGroups)
        {
            if (typeIndex > 0) sb.AppendLine();

            sb.Append("file static class Interceptors_");
            sb.AppendLine(SanitizeIdentifier(containingType));
            sb.AppendLine("{");

            var methodIndex = 0;
            foreach (var group in methods)
            {
                if (methodIndex > 0) sb.AppendLine();

                switch (group.Representative.Target.Mode)
                {
                    case MethodMode.Activity:
                        EmitActivityInterceptor(group.Representative, group.Locations, sb, methodIndex, types);
                        break;
                    case MethodMode.ActivityName:
                        EmitActivityNameInterceptor(group.Representative, group.Locations, sb, methodIndex);
                        break;
                    case MethodMode.SuppressInstrumentation:
                        EmitSuppressInstrumentationInterceptor(group.Representative, group.Locations, sb, methodIndex);
                        break;
                }

                methodIndex++;
            }

            sb.AppendLine("}");
            typeIndex++;
        }

        // Close namespace
        sb.AppendLine("}");

        spc.AddSource("Interceptors.g.cs", sb.ToString());
    }

    #region Grouping

    private record MethodGroup(InterceptCallSite Representative, List<InterceptableLocationInfo> Locations);

    private static List<MethodGroup> GroupCallSitesByMethod(ImmutableArray<InterceptCallSite> callSites)
    {
        var groups = new Dictionary<string, MethodGroup>(StringComparer.Ordinal);

        foreach (var callSite in callSites)
        {
            var key = callSite.Target.MethodSymbolKey;
            if (!groups.TryGetValue(key, out var group))
            {
                group = new MethodGroup(callSite, []);
                groups[key] = group;
            }

            group.Locations.Add(callSite.Location);
        }

        return [.. groups.Values];
    }

    private static List<(string ContainingType, List<MethodGroup> Methods)> GroupMethodsByContainingType(
        List<MethodGroup> methodGroups)
    {
        var typeGroups = new Dictionary<string, List<MethodGroup>>(StringComparer.Ordinal);

        foreach (var group in methodGroups)
        {
            var containingType = group.Representative.ResolvedMethod.ContainingTypeFullName;
            if (!typeGroups.TryGetValue(containingType, out var list))
            {
                list = [];
                typeGroups[containingType] = list;
            }

            list.Add(group);
        }

        return [.. typeGroups.Select(kvp => (kvp.Key, kvp.Value))];
    }

    #endregion

    #region ActivitySourceHolder

    private static Dictionary<string, string> CollectActivitySourceNames(
        ImmutableArray<InterceptCallSite> callSites,
        ImmutableArray<TypeMetadata> types)
    {
        var result = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var type in types)
            if (!string.IsNullOrEmpty(type.ActivitySourceName) && !result.ContainsKey(type.ActivitySourceName))
                result[type.ActivitySourceName] = type.TypeFullName;

        foreach (var callSite in callSites)
        {
            if (callSite.Target.Mode != MethodMode.Activity) continue;

            var activitySourceName = GetActivitySourceName(callSite, types);
            if (!string.IsNullOrEmpty(activitySourceName) && !result.ContainsKey(activitySourceName))
                result[activitySourceName] = callSite.Target.ContainingTypeFullName;
        }

        return result;
    }

    private static string GetActivitySourceName(InterceptCallSite callSite, ImmutableArray<TypeMetadata> types)
    {
        foreach (var type in types)
            if (type.TypeFullName == callSite.Target.ContainingTypeFullName)
                return type.ActivitySourceName;

        return callSite.Target.ContainingTypeFullName;
    }

    private static string GetActivitySourceFieldName(string activitySourceName)
    {
        var sb = new StringBuilder("ActivitySource_");
        foreach (var c in activitySourceName)
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');

        return sb.ToString();
    }

    private static void EmitActivitySourceHolder(
        StringBuilder sb,
        Dictionary<string, string> activitySourceNames,
        string assemblyName)
    {
        sb.AppendLine("public static class ActivitySourceHolder");
        sb.AppendLine("{");

        foreach (var kvp in activitySourceNames)
        {
            var fieldName = GetActivitySourceFieldName(kvp.Key);
            var typeofName = GetTypeofExpression(kvp.Value);

            sb.Append("    internal static readonly global::System.Diagnostics.ActivitySource ");
            sb.Append(fieldName);
            sb.Append(" = new(\"");
            sb.Append(EscapeString(kvp.Key));
            sb.Append("\", typeof(global::");
            sb.Append(typeofName);
            sb.AppendLine(").Assembly.GetName().Version?.ToString());");
        }

        sb.AppendLine();

        // Generate Add{AssemblyName}Sources extension method
        var sanitizedAssemblyName = SanitizeIdentifier(assemblyName);
        sb.AppendLine("    /// <summary>Register all generated ActivitySource instances with the TracerProviderBuilder.</summary>");
        sb.Append("    public static global::OpenTelemetry.Trace.TracerProviderBuilder Add");
        sb.Append(sanitizedAssemblyName);
        sb.AppendLine("Sources(this global::OpenTelemetry.Trace.TracerProviderBuilder builder)");
        sb.AppendLine("    {");

        foreach (var kvp in activitySourceNames)
        {
            sb.Append("        builder.AddSource(\"");
            sb.Append(EscapeString(kvp.Key));
            sb.AppendLine("\");");
        }

        sb.AppendLine();
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string GetTypeofExpression(string typeFullName)
    {
        var backtickIndex = typeFullName.IndexOf('`');
        if (backtickIndex < 0) return typeFullName;

        var arityStr = "";
        var i = backtickIndex + 1;
        while (i < typeFullName.Length && char.IsDigit(typeFullName[i]))
        {
            arityStr += typeFullName[i];
            i++;
        }

        if (!int.TryParse(arityStr, out var arity) || arity <= 0) return typeFullName;

        var baseName = typeFullName[..backtickIndex];
        var rest = i < typeFullName.Length ? typeFullName[i..] : "";
        return baseName + "<" + new string(',', arity - 1) + ">" + rest;
    }

    #endregion

    #region InterceptsLocation Attribute

    private static void EmitInterceptsLocationAttribute(StringBuilder sb)
    {
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    sealed file class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data)");
        sb.AppendLine("        {");
        sb.AppendLine("            _ = version;");
        sb.AppendLine("            _ = data;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    #endregion

    #region Activity Mode Interceptor

    internal static void EmitActivityInterceptor(
        InterceptCallSite callSite, List<InterceptableLocationInfo> locations, StringBuilder sb, int index,
        ImmutableArray<TypeMetadata> types)
    {
        var target = callSite.Target;
        var resolved = callSite.ResolvedMethod;

        foreach (var location in locations)
            EmitInterceptsLocationAttr(sb, location);

        var isAsyncInterceptor = NeedsAsyncInterceptor(resolved);
        EmitMethodSignature(sb, resolved, index, isAsyncInterceptor);

        sb.AppendLine("    {");

        var activitySourceName = types.IsDefaultOrEmpty
            ? target.ContainingTypeFullName
            : GetActivitySourceName(callSite, types);
        var activitySourceFieldName = GetActivitySourceFieldName(activitySourceName);

        sb.Append("        var activity = ActivitySourceHolder.");
        sb.Append(activitySourceFieldName);
        sb.Append(".StartActivity(\"");
        sb.Append(EscapeString(target.ActivityName ?? ""));
        sb.Append('"');
        if (target.Kind is not (null or "default"))
        {
            sb.Append(", ");
            sb.Append(target.Kind);
        }
        else
        {
            sb.Append(", default");
        }

        sb.AppendLine(");");

        if (target.InTags.Length > 0)
        {
            sb.AppendLine();
            sb.AppendLine("        if (activity != null)");
            sb.AppendLine("        {");
            foreach (var tag in target.InTags)
            {
                sb.Append("            activity.SetTag(\"");
                sb.Append(EscapeString(tag.TagName));
                sb.Append("\", ");
                sb.Append(GetTagValueExpression(tag, target.ContainingTypeFullName));
                sb.AppendLine(");");
            }

            sb.AppendLine("        }");
        }

        if (target.SuppressInstrumentation)
        {
            sb.AppendLine();
            sb.AppendLine("        var disposable = global::OpenTelemetry.SuppressInstrumentationScope.Begin();");
        }

        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");

        EmitOriginalMethodCall(sb, resolved, isAsyncInterceptor);

        if (target.OutTags.Length > 0)
        {
            sb.AppendLine();
            sb.AppendLine("            if (activity != null)");
            sb.AppendLine("            {");
            foreach (var tag in target.OutTags)
            {
                var tagName = tag.TagName;
                foreach (var inTag in target.InTags)
                {
                    if (inTag.TagName != tagName) continue;

                    tagName += "$out";
                    break;
                }

                sb.Append("                activity.SetTag(\"");
                sb.Append(EscapeString(tagName));
                sb.Append("\", ");
                sb.Append(GetTagValueExpression(tag, target.ContainingTypeFullName));
                sb.AppendLine(");");
            }

            sb.AppendLine("            }");
        }

        if (!resolved.ReturnType.IsVoid && !IsVoidTask(resolved.ReturnType))
        {
            sb.AppendLine();
            sb.AppendLine("            return @return;");
        }

        sb.AppendLine("        }");
        sb.AppendLine("        catch (global::System.Exception ex) when (global::OpenTelemetry.Proxy.ActivityExtensions.SetExceptionStatus(activity, ex))");
        sb.AppendLine("        {");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("        finally");
        sb.AppendLine("        {");
        if (target.SuppressInstrumentation)
            sb.AppendLine("            disposable?.Dispose();");

        sb.AppendLine("            activity?.Dispose();");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
    }

    #endregion

    #region ActivityName Mode Interceptor

    internal static void EmitActivityNameInterceptor(
        InterceptCallSite callSite, List<InterceptableLocationInfo> locations, StringBuilder sb, int index)
    {
        var target = callSite.Target;
        var resolved = callSite.ResolvedMethod;

        foreach (var location in locations)
            EmitInterceptsLocationAttr(sb, location);

        var isAsyncInterceptor = NeedsAsyncInterceptor(resolved);
        EmitMethodSignature(sb, resolved, index, isAsyncInterceptor);

        sb.AppendLine("    {");

        if (target.InTags.Length > 0)
        {
            sb.AppendLine("        var tags = new global::System.Collections.Generic.Dictionary<string, object?>");
            sb.AppendLine("        {");
            for (var i = 0; i < target.InTags.Length; i++)
            {
                var tag = target.InTags[i];
                sb.Append("            { \"");
                sb.Append(EscapeString(tag.TagName));
                sb.Append("\", ");
                sb.Append(GetTagValueExpression(tag, target.ContainingTypeFullName));
                sb.Append(" }");
                if (i < target.InTags.Length - 1) sb.Append(',');

                sb.AppendLine();
            }

            sb.AppendLine("        };");
            sb.AppendLine();
        }

        sb.Append("        using (global::OpenTelemetry.Proxy.InnerActivityAccessor.SetActivityContext(new global::OpenTelemetry.Proxy.InnerActivityContext { AdjustStartTime = ");
        sb.Append(target.AdjustStartTime ? "true" : "false");
        sb.Append(", Name = \"");
        sb.Append(EscapeString(target.ActivityName ?? ""));
        sb.Append('"');
        if (target.InTags.Length > 0)
            sb.Append(", Tags = tags");

        sb.AppendLine(" }))");
        sb.AppendLine("        {");

        if (isAsyncInterceptor)
            EmitOriginalMethodCallAsync(sb, resolved);
        else
            EmitOriginalMethodCallSimple(sb, resolved);

        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    #endregion

    #region SuppressInstrumentation Mode Interceptor

    internal static void EmitSuppressInstrumentationInterceptor(
        InterceptCallSite callSite, List<InterceptableLocationInfo> locations, StringBuilder sb, int index)
    {
        var resolved = callSite.ResolvedMethod;

        foreach (var location in locations)
            EmitInterceptsLocationAttr(sb, location);

        EmitMethodSignature(sb, resolved, index, isAsync: false);

        sb.AppendLine("    {");
        sb.AppendLine("        using (global::OpenTelemetry.SuppressInstrumentationScope.Begin())");
        sb.AppendLine("        {");

        EmitOriginalMethodCallSimple(sb, resolved);

        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    #endregion

    #region Method Signature Generation

    private static void EmitInterceptsLocationAttr(StringBuilder sb, InterceptableLocationInfo location)
    {
        sb.Append("    [global::System.Runtime.CompilerServices.InterceptsLocation(");
        sb.Append(location.Version);
        sb.Append(", \"");
        sb.Append(EscapeString(location.Data));
        sb.AppendLine("\")]");
    }

    private static void EmitMethodSignature(
        StringBuilder sb,
        ResolvedMethodInfo resolved,
        int index,
        bool isAsync)
    {
        sb.AppendLine("#if NET6_0_OR_GREATER");
        sb.AppendLine("    [global::System.Diagnostics.StackTraceHidden]");
        sb.AppendLine("#endif");
        sb.Append("    internal static ");
        if (isAsync) sb.Append("async ");

        sb.Append(resolved.ReturnType.TypeFullName);
        sb.Append(' ');
        sb.Append(resolved.MethodName);
        sb.Append("_Intercept_");
        sb.Append(index);

        if (resolved.TypeArguments.Length > 0)
        {
            sb.Append('<');
            for (var i = 0; i < resolved.TypeArguments.Length; i++)
            {
                if (i > 0) sb.Append(", ");

                sb.Append(resolved.TypeArguments[i]);
            }

            sb.Append('>');
        }

        sb.Append('(');

        var paramIndex = 0;

        // Instance methods: add `this T @this` as first parameter
        if (!resolved.IsStatic)
        {
            sb.Append("this ");
            sb.Append(resolved.ContainingTypeFullName);
            sb.Append(" @this");
            paramIndex++;
        }

        foreach (var param in resolved.Parameters)
        {
            if (paramIndex > 0) sb.Append(", ");

            switch (param.RefKind)
            {
                case RefKind.Ref:
                    sb.Append("ref ");
                    break;
                case RefKind.Out:
                    sb.Append("out ");
                    break;
                case RefKind.In:
                    sb.Append("in ");
                    break;
                case RefKind.RefReadonlyParameter:
                    sb.Append("ref readonly ");
                    break;
            }

            sb.Append(param.TypeFullName);
            sb.Append(' ');
            sb.Append(param.Name);
            paramIndex++;
        }

        sb.Append(')');

        // Emit generic type constraints (where clauses)
        if (resolved.GenericConstraints.Length > 0)
        {
            foreach (var constraint in resolved.GenericConstraints)
            {
                sb.AppendLine();
                sb.Append("        where ");
                sb.Append(constraint.TypeParameterName);
                sb.Append(" : ");
                sb.Append(constraint.ConstraintClause);
            }
        }

        sb.AppendLine();
    }

    #endregion

    #region Original Method Call Generation

    private static bool NeedsAsyncInterceptor(ResolvedMethodInfo resolved) =>
        !resolved.ReturnType.IsVoid && (resolved.ReturnType.IsTask || resolved.ReturnType.IsValueTask);

    private static bool IsVoidTask(ReturnTypeInfo returnType) =>
        (returnType.IsTask || returnType.IsValueTask) && !returnType.TypeFullName.Contains("<");

    private static void EmitOriginalMethodCall(
        StringBuilder sb,
        ResolvedMethodInfo resolved,
        bool isAsyncInterceptor)
    {
        var callExpression = BuildOriginalCallExpression(resolved);

        if (resolved.ReturnType.IsVoid)
        {
            sb.Append("            ");
            sb.Append(callExpression);
            sb.AppendLine(";");
        }
        else if (isAsyncInterceptor && !IsVoidTask(resolved.ReturnType))
        {
            sb.Append("            var @return = await ");
            sb.Append(callExpression);
            sb.AppendLine(".ConfigureAwait(false);");
        }
        else if (isAsyncInterceptor)
        {
            sb.Append("            await ");
            sb.Append(callExpression);
            sb.AppendLine(".ConfigureAwait(false);");
        }
        else
        {
            sb.Append("            var @return = ");
            sb.Append(callExpression);
            sb.AppendLine(";");
        }
    }

    private static void EmitOriginalMethodCallSimple(
        StringBuilder sb,
        ResolvedMethodInfo resolved)
    {
        var callExpression = BuildOriginalCallExpression(resolved);

        if (resolved.ReturnType.IsVoid)
        {
            sb.Append("            ");
            sb.Append(callExpression);
            sb.AppendLine(";");
        }
        else
        {
            sb.Append("            return ");
            sb.Append(callExpression);
            sb.AppendLine(";");
        }
    }

    private static void EmitOriginalMethodCallAsync(
        StringBuilder sb,
        ResolvedMethodInfo resolved)
    {
        var callExpression = BuildOriginalCallExpression(resolved);

        if (IsVoidTask(resolved.ReturnType))
        {
            sb.Append("            await ");
            sb.Append(callExpression);
            sb.AppendLine(".ConfigureAwait(false);");
        }
        else
        {
            sb.Append("            return await ");
            sb.Append(callExpression);
            sb.AppendLine(".ConfigureAwait(false);");
        }
    }

    private static string BuildOriginalCallExpression(ResolvedMethodInfo resolved)
    {
        var sb = new StringBuilder();

        if (resolved.IsStatic)
        {
            sb.Append(resolved.ContainingTypeFullName);
            sb.Append('.');
        }
        else
        {
            sb.Append("@this.");
        }

        sb.Append(resolved.MethodName);
        sb.Append('(');

        var first = true;
        foreach (var param in resolved.Parameters)
        {
            if (!first) sb.Append(", ");

            first = false;

            switch (param.RefKind)
            {
                case RefKind.Ref:
                    sb.Append("ref ");
                    break;
                case RefKind.Out:
                    sb.Append("out ");
                    break;
            }

            sb.Append(param.Name);
        }

        sb.Append(')');

        return sb.ToString();
    }

    #endregion

    #region Tag Value Expression Generation

    private static string GetTagValueExpression(TagMetadata tag, string containingTypeFullName)
    {
        var baseName = tag.Source switch
        {
            TagSource.InstanceFieldOrProperty => "@this." + tag.SourceName,
            TagSource.StaticFieldOrProperty => "global::" + containingTypeFullName + "." + tag.SourceName,
            TagSource.ReturnValue => "@return",
            _ => tag.SourceName
        };

        return AppendExpression(baseName, tag.Expression);
    }

    private static string AppendExpression(string baseName, string? expression)
    {
        if (string.IsNullOrWhiteSpace(expression)) return baseName;

        return expression![0] == '$' ? baseName + expression[1..] : baseName;
    }

    #endregion

    #region Helpers

    private static string EscapeString(string value) =>
        value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");

    private static string SanitizeIdentifier(string name)
    {
        // Strip "global::" prefix if present (from FullyQualifiedFormat)
        if (name.StartsWith("global::", StringComparison.Ordinal))
            name = name.Substring(8);

        var sb = new StringBuilder(name.Length);

        foreach (var c in name)
        {
            if (c is '+' or '-' or '*' or '/' or '%' or
                    '>' or '<' or '=' or '!' or '&' or '|' or '^' or
                    '#' or '$' or '~' or '?' or ':' or ';' or ',' or '\'' or '"' or
                    '(' or ')' or '[' or ']' or '{' or '}' ||
                char.IsWhiteSpace(c))
                sb.Append('_');
            else if (c == '@')
                sb.Append(sb.Length == 0 ? '@' : '_');
            else if (c is not '.') sb.Append(c);
        }

        return sb.ToString();
    }

    #endregion
}
